// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: Proto/Proto.proto

package Proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MutualExclusionService_SendRequest_FullMethodName    = "/Proto.MutualExclusionService/SendRequest"
	MutualExclusionService_ReceiveRequest_FullMethodName = "/Proto.MutualExclusionService/ReceiveRequest"
)

// MutualExclusionServiceClient is the client API for MutualExclusionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MutualExclusionServiceClient interface {
	// Sends a request to access the critical section.
	SendRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	// Receives a request from another node.
	ReceiveRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type mutualExclusionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMutualExclusionServiceClient(cc grpc.ClientConnInterface) MutualExclusionServiceClient {
	return &mutualExclusionServiceClient{cc}
}

func (c *mutualExclusionServiceClient) SendRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, MutualExclusionService_SendRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mutualExclusionServiceClient) ReceiveRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, MutualExclusionService_ReceiveRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MutualExclusionServiceServer is the server API for MutualExclusionService service.
// All implementations must embed UnimplementedMutualExclusionServiceServer
// for forward compatibility
type MutualExclusionServiceServer interface {
	// Sends a request to access the critical section.
	SendRequest(context.Context, *Request) (*Reply, error)
	// Receives a request from another node.
	ReceiveRequest(context.Context, *Request) (*Reply, error)
	mustEmbedUnimplementedMutualExclusionServiceServer()
}

// UnimplementedMutualExclusionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMutualExclusionServiceServer struct {
}

func (UnimplementedMutualExclusionServiceServer) SendRequest(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRequest not implemented")
}
func (UnimplementedMutualExclusionServiceServer) ReceiveRequest(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveRequest not implemented")
}
func (UnimplementedMutualExclusionServiceServer) mustEmbedUnimplementedMutualExclusionServiceServer() {
}

// UnsafeMutualExclusionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MutualExclusionServiceServer will
// result in compilation errors.
type UnsafeMutualExclusionServiceServer interface {
	mustEmbedUnimplementedMutualExclusionServiceServer()
}

func RegisterMutualExclusionServiceServer(s grpc.ServiceRegistrar, srv MutualExclusionServiceServer) {
	s.RegisterService(&MutualExclusionService_ServiceDesc, srv)
}

func _MutualExclusionService_SendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MutualExclusionServiceServer).SendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MutualExclusionService_SendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MutualExclusionServiceServer).SendRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MutualExclusionService_ReceiveRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MutualExclusionServiceServer).ReceiveRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MutualExclusionService_ReceiveRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MutualExclusionServiceServer).ReceiveRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// MutualExclusionService_ServiceDesc is the grpc.ServiceDesc for MutualExclusionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MutualExclusionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Proto.MutualExclusionService",
	HandlerType: (*MutualExclusionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRequest",
			Handler:    _MutualExclusionService_SendRequest_Handler,
		},
		{
			MethodName: "ReceiveRequest",
			Handler:    _MutualExclusionService_ReceiveRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Proto/Proto.proto",
}
